// names of images
var pictures = [
  "again.jpg",
  "air.jpg",
  "ball.jpg",
  "blue.jpg",
  "branch.jpg",
  "capsule.jpg",
  "cesta.jpg",
  "forest.jpg",
  "golf.jpg",
  "grass.jpg",
  "life.jpg",
  "never.jpg",
  "one.jpg",
  "paper.jpg",
  "park.jpg",
  "path.jpg",
  "road.jpg",
  "secret.jpg",
  "semi.jpg",
  "star.jpg",
  "trees.jpg",
  "two.jpg",
  "winter.jpg",
  "zivot.jpg"
];

var words = [
  "accommodate | adapt, assist, house",
  "adverse | unfavorable, opposing",
  "alienate | estrange, antagonize find a place to rest",
  "anarchy | absence of government, chaos",
  "apposite | apt",
  "assent | agree",
  "badger | pester",
  "benefactor | patron",
  "bovine | cow-like",
  "canon | rule",
  "cessation | a stopping",
  "coalesce | combine",
  "comprise | consist of",
  "conscription | draft, enlistment",
  "convivial | sociable, festive",
  "cudgel | club",
  "decree | official order",
  "denouement | resolution",
  "dichotomy | a division into two parts",
  "dispatch | send",
  "dolorous | gloomy",
  "elaboration | detailed explanation",
  "endemic | peculiar to a particular region",
  "equable | even-tempered",
  "exacting | demanding, difficult",
  "extraneous | not essential",
  "ferment | turmoil",
  "forsake | abandon",
  "gingivitis | inflammation of the gums",
  "havoc | destruction, chaos",
  "idiosyncrasy | peculiarity",
  "implosion | bursting inward",
  "incognito | disguised",
  "infatuate | immature love",
  "insufferable | unbearable",
  "irascible | irritable",
  "lachrymose | tearful",
  "lissome | agile, supple",
  "mandrill | baboon",
  "mentor | teacher",
  "monolithic | large and uniform",
  "negligible | insignificant",
  "oblong | elliptical, oval",
  "orator | speaker",
  "panache | flamboyance",
  "pastoral | rustic",
  "perdition | damnation",
  "pettifogger | unscrupulous lawyer",
  "plentiful | abundant",
  "precept | principle, law",
  "prevaricate | lie",
  "promontory | headland, cape",
  "proxy | substitute, agent",
  "quadruped | four foot animal",
  "randy | vulgar",
  "recuperation | recovery",
  "render | deliver, provide",
  "resound | echo",
  "risque  | off-color, racy",
  "satanic | pertaining to the Devil",
  "sedentary | stationary, inactive",
  "shoal | reef",
  "sloth | laziness",
  "specious | false but plausible reasoning",
  "stevedore | longshoreman",
  "subvert | undermine",
  "syllabicate | divide into syllables",
  "tempo | speed",
  "tryst | meeting, rendezvous",
  "unstinting | generous",
  "viaduct | waterway",
  "wary | guarded, cautious"
];